# Test Actions train a model on Azure Machine Learning  
name: aml-train-deploy-workflow 
on:
  push:
    branches:
      - master
    paths:
      - '.cloud/.azure/arm_deploy.json'
      - '.cloud/.azure/arm_deploy.params.json'
  repository_dispatch:
   types: [testRun]
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
        
    # Connect or Create the Azure Machine Learning Workspace
    - name: deploy all resources
      id: aml_configure
      uses: mlopstemplates/aml_configure@master
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          armtemplate_file: "arm_deploy.json"
          armtemplateparams_file: "arm_deploy.params.json"
          resource_group: "TestFlow2"
          pattoken: ${{secrets.PATTOKEN}}
          gitrepo: ${{github.repository}}      
