# Actions train a model on Azure Machine Learning
name: aml-train
on:
  push:
    branches:
      - master
 
  repository_dispatch:
    types: [runFailed]
 
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
        
    # Connect or Create the Azure Machine Learning Workspace
    - name: Connect/Create Azure Machine Learning Workspace
      id: aml_workspace
      uses: Azure/aml-workspace@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}


    # - uses: actions/upload-artifact@v1
    #   with:
    #     name: ${{ steps.aml_run.outputs.model }}
    #     path: SpatialSimOutputs

